export const queryKeys = {
  popularMovies: "popular-movies",
  upcomingMovies: "upcoming-movies",
  topTvShows: "popular-tv-shows",
  movies: "movies",
  cast: "cast",
  recom: "recom",
  tvshows: "tvshows",
  video: "video",
  tvShowRecom: "tvShowRecom",
  tvShowCast: "tvShowCast",
  crew: "crew",
  tvShowCrew: "tvShowCrew",
  airTvShows: "air-tv-shows",
  pages: "pages",
  genreList: "genre-list",
  genres: "genres",
  search: "search",
};
